version: '3'

services:
  iot-app:
    build: .
    ports:
      - "1111:5000"
    volumes:
      - iot-data:/data
    restart: unless-stopped
    environment:
      - DATABASE=/data/iot.db
      - PORT=5000

volumes:
  iot-data:
    driver: local 